spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource # 使用druid数据源
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.97.155:3306/wms?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&&serverTimezone=GMT
    username: root
    password: root
    # 连接池补充配置
    initialSize: 5 #初始化时建立物理连接地个数。
    minIdle: 5 #最小连接池数量
    maxActive: 20 #最大连接池数量
    maxWait: 60000 #配置获取连接等待超时的时间
    timeBetweenEvictionRunsMillis: 60000 #配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
    minEvictableIdleTimeMillis: 300000 # 配置一个连接在池中最小生存的时间，单位是毫秒
    validationQuery: select 1 #验证连接有效与否地sql，不同数据库配置不同
    testWhileIdle: true #建议配置为true，不影响性能，并且保证安全性。申请连接的时候检测，如果空闲时间大于timeBetweenEvictionRunsMillis，执行validationQuery检测连接是否有效。
    testOnBorrow: true #申请连接时执行validationQuery检测连接是否有效，做了这个配置会降低性能。这里建议配置为TRUE，防止取到的连接不可用
    testOnReturn: false #归还连接时执行validationQuery检测连接是否有效，做了这个配置会降低性能
    poolPreparedStatements: true # 是否缓存preparedStatement，也就是PSCache,PSCache对支持游标的数据库性能提升巨大，比如说oracle。在mysql5.5以下的版本中没有PSCache功能，建议关闭掉
    maxOpenPreparedStatements: 20 #指定每个连接上PSCache的大小
    filters: stat,wall,log4j # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000 # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
    # 合并多个DruidDataSource的监控数据
    useGlobalDataSourceStat: true

mybatis-plus:
  mapper-locations: mapper/*.xml #如果是放在src/main/java目录下 classpath:/com/yourpackage/*/mapper/*Mapper.xml;如果是放在resource目录 classpath:/mapper/*Mapper.xml
  type-aliases-package: com.hczx.wms.entity #实体扫描，多个package用逗号或者分号分隔
  global-config:
    id-type: 2 #主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
    field-strategy: 2 #字段策略 0:"忽略判断",1:"非 NULL 判断"),2:"非空判断"
    capital-mode: false #数据库大写下划线转换
    refresh-mapper: true
    db-type: MYSQL #数据库类型
  #配置
  configuration:
    #是否开启自动驼峰命名规则映射:从数据库列名到Java属性驼峰命名的类似映射，配置返回数据库(column下划线命名&&返回java实体是驼峰命名)，自动匹配无需as（没开启这个，SQL需要写as： select user_id as userId）
    map-underscore-to-camel-case: true
    cache-enabled: false
    #返回map时true:当查询数据为空时字段返回为null,false:不加这个查询数据为空时，字段将被隐藏
    call-setters-on-nulls: true
    # 这个配置会将执行的sql打印出来，在开发或测试的时候可以用
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl